repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        pass_filenames: true
        types: [python]
      - id: pytest
        name: pytest
        entry: poetry run pytest .
        language: system
        always_run: true
        pass_filenames: false
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort
        pass_filenames: true
        language: system
        types: [python]
