repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        pass_filenames: true
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        language: system
        pass_filenames: true
        types: [python]
      - id: pytest
        name: pytest
        entry: poetry run pytest .
        language: system
        always_run: true
        pass_filenames: false
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        pass_filenames: true
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        pass_filenames: true
        language: system
        args: ["--explicit-package-bases", "--ignore-missing-imports", "--exclude", "pulumi"]
        types: [python]
